# This is a basic workflow to help you get started with Actions

name: Build & Deploy
on:
  push:
     branches: [master]
jobs:
  deploy:
     runs-on: ubuntu-latest
     steps:
        - name: Deploy NodeJS app
          uses: appleboy/ssh-action@v0.1.2
          with:
             host: ${{secrets.SSH_HOST}} # IP address of digital ocean server
             key: ${{secrets.SSH_KEY}} #private or public key from digitl ocean
             username: ${{ secrets.SSH_USERNAME }} #root user of digital ocean droplet  	     
             script: |
                mkdir jungfolder  #name of directory you want to deploy in live server 
                cd jungfolder #cd to the folder
                git clone git@github.com:guevarrajr/smartcar/edit/main/.github #(to clone the repository to Digitalocean folder.)
                echo 'Deployment successful to Digital Ocean'  (this is a messge)
