# This is a basic workflow to help you get started with Actions

name: Pull from GitHub
      - name: Pull from GitHub
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: cd ~/smartcar/ && git pull git@github.com:guevarrajr/smartcar.git
